[package]
name = "mammut"
version = "0.6.1"
description = "A wrapper around the Mastodon API."
authors = ["Aaron Power <theaaronepower@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Aaronepower/mammut.git"
keywords = ["api", "web", "social", "mastodon", "wrapper"]
categories = ["web-programming", "http-client"]

[dependencies]
reqwest = "0.5"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
ws = { git = "https://github.com/housleyjk/ws-rs.git", version = "0.7.1" }
websocket = { git = "https://github.com/cyderize/rust-websocket.git", version = "0.19.2" }
crossbeam = "0.2"
url = "1.4.0"



[dependencies.chrono]
# Locked to 0.3.0 since chrono 0.3.1 uses serde ^1, which is incompatible
# with serde 0.9 specified above.
version = "=0.3.0"
features = ["serde"]
